package com.pamirs.takin.entity.dao.assist.loaddata;

import java.util.List;
import java.util.Map;

import com.pamirs.takin.entity.domain.entity.TReturnData;
import com.pamirs.takin.entity.domain.vo.TReturnDataVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TReturnDataDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return_data
     *
     * @mbg generated
     */
    int deleteByPrimaryKey(Long trdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return_data
     *
     * @mbg generated
     */
    int insert(TReturnData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return_data
     *
     * @mbg generated
     */
    int insertSelective(TReturnData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return_data
     *
     * @mbg generated
     */
    TReturnData selectByPrimaryKey(Long trdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return_data
     *
     * @mbg generated
     */
    int updateByPrimaryKeySelective(TReturnData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return_data
     *
     * @mbg generated
     */
    int updateByPrimaryKey(TReturnData record);

    /**
     * 查询是否存在  相同技术链路id 或者 相同 startClass的 抽数配置
     *
     * @param incJarConfigVo
     * @return
     */
    List<TReturnDataVo> queryJarNameAndStartClass(TReturnDataVo incJarConfigVo);

    /**
     * 获取抽数配置分页
     *
     * @param paramMap
     * @return
     */
    List<TReturnDataVo> queryReturnDataPage(Map<String, Object> paramMap);

    /**
     * 查询详情
     *
     * @param trdId
     * @return
     */
    TReturnDataVo queryReturnDataDetail(@Param("trdId") String trdId);

    /**
     * 批量删除
     *
     * @param trdIdList
     * @return
     */
    int deleteByTrdIdList(@Param("trdIdList") List<String> trdIdList);

    /**
     * 通过idList查询
     *
     * @param trdIdList
     * @return
     */
    List<TReturnData> queryByTrdIdList(@Param("trdIdList") List<String> trdIdList);

    /**
     * 批量更细状态
     *
     * @param trdIdList
     * @param loadStatus
     * @return
     */
    int updateLoadStatusByTrdIdList(@Param("trdIdList") List<String> trdIdList,
        @Param("loadStatus") Integer loadStatus);

    /**
     * 查询所有插件
     *
     * @return
     */
    List<TReturnDataVo> selectAll();
}
