package com.pamirs.takin.entity.domain.entity;

import lombok.Data;

@Data
public class DsModelWithBLOBs extends DsModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_ds_manage.CONFIG
     *
     * mbg generated
     */
    private String config;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_ds_manage.PARSE_CONFIG
     *
     * @mbg generated
     */
    private String parseConfig;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_ds_manage
     *
     * @mbg generated
     */
    public DsModelWithBLOBs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_ds_manage.CONFIG
     *
     * @return the value of t_application_ds_manage.CONFIG
     * @mbg generated
     */
    public String getConfig() {
        return config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_ds_manage.CONFIG
     *
     * @param config the value for t_application_ds_manage.CONFIG
     * @mbg generated
     */
    public void setConfig(String config) {
        this.config = config == null ? null : config.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_ds_manage.PARSE_CONFIG
     *
     * @return the value of t_application_ds_manage.PARSE_CONFIG
     * @mbg generated
     */
    public String getParseConfig() {
        return parseConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_ds_manage.PARSE_CONFIG
     *
     * @param parseConfig the value for t_application_ds_manage.PARSE_CONFIG
     * @mbg generated
     */
    public void setParseConfig(String parseConfig) {
        this.parseConfig = parseConfig == null ? null : parseConfig.trim();
    }
}
