package com.pamirs.takin.entity.domain.entity;

import java.util.Date;

public class LinkBottleneck {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_link_bottleneck.ID
     *
     * @mbg generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_link_bottleneck.APP_NAME
     *
     * @mbg generated
     */
    private String appName;

    private String keyWords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_link_bottleneck.BOTTLENECK_TYPE
     *
     * @mbg generated
     */
    private int bottleneckType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_link_bottleneck.BOTTLENECK_LEVEL
     *
     * @mbg generated
     */
    private int bottleneckLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_link_bottleneck.CREATE_TIME
     *
     * @mbg generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_link_bottleneck.MODIFY_TIME
     *
     * @mbg generated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_link_bottleneck.ACTIVE
     *
     * @mbg generated
     */
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_link_bottleneck.CONTENT
     *
     * @mbg generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_link_bottleneck.CONTENT
     *
     * @mbg generated
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_link_bottleneck
     *
     * @mbg generated
     */
    public LinkBottleneck(Long id, String appName,
        int bottleneckType,
        int bottleneckLevel,
        Date createTime,
        Date modifyTime,
        String active,
        String content,
        String text,
        String keyWords) {
        this.id = id;
        this.appName = appName;
        this.bottleneckType = bottleneckType;
        this.bottleneckLevel = bottleneckLevel;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
        this.active = active;
        this.content = content;
        this.keyWords = keyWords;
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_link_bottleneck
     *
     * @mbg generated
     */
    public LinkBottleneck() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link_bottleneck.ID
     *
     * @return the value of t_link_bottleneck.ID
     * @mbg generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link_bottleneck.ID
     *
     * @param id the value for t_link_bottleneck.ID
     * @mbg generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link_bottleneck.APP_NAME
     *
     * @return the value of t_link_bottleneck.APP_NAME
     * @mbg generated
     */
    public String getKeyWords() {
        return keyWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link_bottleneck.APP_NAME
     *
     * @param keyWords the value for t_link_bottleneck.APP_NAME
     * @mbg generated
     */
    public void setKeyWords(String keyWords) {
        this.keyWords = keyWords == null ? null : keyWords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link_bottleneck.APP_NAME
     *
     * @return the value of t_link_bottleneck.APP_NAME
     * @mbg generated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link_bottleneck.APP_NAME
     *
     * @param appName the value for t_link_bottleneck.APP_NAME
     * @mbg generated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link_bottleneck.BOTTLENECK_TYPE
     *
     * @return the value of t_link_bottleneck.BOTTLENECK_TYPE
     * @mbg generated
     */
    public int getBottleneckType() {
        return bottleneckType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link_bottleneck.BOTTLENECK_TYPE
     *
     * @param bottleneckType the value for t_link_bottleneck.BOTTLENECK_TYPE
     * @mbg generated
     */
    public void setBottleneckType(int bottleneckType) {
        this.bottleneckType = bottleneckType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link_bottleneck.BOTTLENECK_LEVEL
     *
     * @return the value of t_link_bottleneck.BOTTLENECK_LEVEL
     * @mbg generated
     */
    public int getBottleneckLevel() {
        return bottleneckLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link_bottleneck.BOTTLENECK_LEVEL
     *
     * @param bottleneckLevel the value for t_link_bottleneck.BOTTLENECK_LEVEL
     * @mbg generated
     */
    public void setBottleneckLevel(int bottleneckLevel) {
        this.bottleneckLevel = bottleneckLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link_bottleneck.CREATE_TIME
     *
     * @return the value of t_link_bottleneck.CREATE_TIME
     * @mbg generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link_bottleneck.CREATE_TIME
     *
     * @param createTime the value for t_link_bottleneck.CREATE_TIME
     * @mbg generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link_bottleneck.MODIFY_TIME
     *
     * @return the value of t_link_bottleneck.MODIFY_TIME
     * @mbg generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link_bottleneck.MODIFY_TIME
     *
     * @param modifyTime the value for t_link_bottleneck.MODIFY_TIME
     * @mbg generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link_bottleneck.ACTIVE
     *
     * @return the value of t_link_bottleneck.ACTIVE
     * @mbg generated
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link_bottleneck.ACTIVE
     *
     * @param active the value for t_link_bottleneck.ACTIVE
     * @mbg generated
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link_bottleneck.CONTENT
     *
     * @return the value of t_link_bottleneck.CONTENT
     * @mbg generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link_bottleneck.CONTENT
     *
     * @param content the value for t_link_bottleneck.CONTENT
     * @mbg generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link_bottleneck.CONTENT
     *
     * @return the value of t_link_bottleneck.CONTENT
     * @mbg generated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link_bottleneck.CONTENT
     *
     * @param text the value for t_link_bottleneck.CONTENT
     * @mbg generated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}
