package com.pamirs.takin.entity.domain.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.pamirs.takin.common.util.DateToStringFormatSerialize;
import org.springframework.format.annotation.DateTimeFormat;

public class NetworkIsolateConfig implements Serializable {
    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_network_isolate_config.ID
     *
     * @mbg generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_network_isolate_config.APP_NAME
     *
     * @mbg generated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_network_isolate_config.VIP_ADDR
     *
     * @mbg generated
     */
    private String vipAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_network_isolate_config.BALANCE_TYPE
     *
     * @mbg generated
     */
    private String balanceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_network_isolate_config.POOL_NAME
     *
     * @mbg generated
     */
    private String poolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_network_isolate_config.ISOLATED_STATUS
     *
     * @mbg generated
     */
    private Integer isolatedStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_network_isolate_config.ACTIVE
     *
     * @mbg generated
     */
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_network_isolate_config.CREATE_TIME
     *
     * @mbg generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonSerialize(using = DateToStringFormatSerialize.class)
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_network_isolate_config.UPDATE_TIME
     *
     * @mbg generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonSerialize(using = DateToStringFormatSerialize.class)
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_network_isolate_config.FAILED_DETAIL
     *
     * @mbg generated
     */
    private String failedDetail;

    private String isolatedIP;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_network_isolate_config
     *
     * @mbg generated
     */
    public NetworkIsolateConfig(Long id, String appName, String vipAddr, String balanceType, String poolName,
        Integer isolatedStatus, String active, Date createTime, Date updateTime, String failedDetail,
        String isolatedIP) {
        this.id = id;
        this.appName = appName;
        this.vipAddr = vipAddr;
        this.balanceType = balanceType;
        this.poolName = poolName;
        this.isolatedStatus = isolatedStatus;
        this.active = active;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.failedDetail = failedDetail;
        this.isolatedIP = isolatedIP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_network_isolate_config
     *
     * @mbg generated
     */
    public NetworkIsolateConfig() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_network_isolate_config.ID
     *
     * @return the value of t_network_isolate_config.ID
     * @mbg generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_network_isolate_config.ID
     *
     * @param id the value for t_network_isolate_config.ID
     * @mbg generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_network_isolate_config.APP_NAME
     *
     * @return the value of t_network_isolate_config.APP_NAME
     * @mbg generated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_network_isolate_config.APP_NAME
     *
     * @param appName the value for t_network_isolate_config.APP_NAME
     * @mbg generated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_network_isolate_config.VIP_ADDR
     *
     * @return the value of t_network_isolate_config.VIP_ADDR
     * @mbg generated
     */
    public String getVipAddr() {
        return vipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_network_isolate_config.VIP_ADDR
     *
     * @param vipAddr the value for t_network_isolate_config.VIP_ADDR
     * @mbg generated
     */
    public void setVipAddr(String vipAddr) {
        this.vipAddr = vipAddr == null ? null : vipAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_network_isolate_config.BALANCE_TYPE
     *
     * @return the value of t_network_isolate_config.BALANCE_TYPE
     * @mbg generated
     */
    public String getBalanceType() {
        return balanceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_network_isolate_config.BALANCE_TYPE
     *
     * @param balanceType the value for t_network_isolate_config.BALANCE_TYPE
     * @mbg generated
     */
    public void setBalanceType(String balanceType) {
        this.balanceType = balanceType == null ? null : balanceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_network_isolate_config.POOL_NAME
     *
     * @return the value of t_network_isolate_config.POOL_NAME
     * @mbg generated
     */
    public String getPoolName() {
        return poolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_network_isolate_config.POOL_NAME
     *
     * @param poolName the value for t_network_isolate_config.POOL_NAME
     * @mbg generated
     */
    public void setPoolName(String poolName) {
        this.poolName = poolName == null ? null : poolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_network_isolate_config.ISOLATED_STATUS
     *
     * @return the value of t_network_isolate_config.ISOLATED_STATUS
     * @mbg generated
     */
    public Integer getIsolatedStatus() {
        return isolatedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_network_isolate_config.ISOLATED_STATUS
     *
     * @param isolatedStatus the value for t_network_isolate_config.ISOLATED_STATUS
     * @mbg generated
     */
    public void setIsolatedStatus(Integer isolatedStatus) {
        this.isolatedStatus = isolatedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_network_isolate_config.ACTIVE
     *
     * @return the value of t_network_isolate_config.ACTIVE
     * @mbg generated
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_network_isolate_config.ACTIVE
     *
     * @param active the value for t_network_isolate_config.ACTIVE
     * @mbg generated
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_network_isolate_config.CREATE_TIME
     *
     * @return the value of t_network_isolate_config.CREATE_TIME
     * @mbg generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_network_isolate_config.CREATE_TIME
     *
     * @param createTime the value for t_network_isolate_config.CREATE_TIME
     * @mbg generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_network_isolate_config.UPDATE_TIME
     *
     * @return the value of t_network_isolate_config.UPDATE_TIME
     * @mbg generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_network_isolate_config.UPDATE_TIME
     *
     * @param updateTime the value for t_network_isolate_config.UPDATE_TIME
     * @mbg generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_network_isolate_config.FAILED_DETAIL
     *
     * @return the value of t_network_isolate_config.FAILED_DETAIL
     * @mbg generated
     */
    public String getFailedDetail() {
        return failedDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_network_isolate_config.FAILED_DETAIL
     *
     * @param failedDetail the value for t_network_isolate_config.FAILED_DETAIL
     * @mbg generated
     */
    public void setFailedDetail(String failedDetail) {
        this.failedDetail = failedDetail == null ? null : failedDetail.trim();
    }

    public String getIsolatedIP() {
        return isolatedIP;
    }

    public void setIsolatedIP(String isolatedIP) {
        this.isolatedIP = isolatedIP;
    }

}
