package com.pamirs.takin.entity.domain.entity;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.TableField;

public class TPressureTimeRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pressure_time_record.RECORD_ID
     *
     * @mbggenerated
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pressure_time_record.START_TIME
     *
     * @mbggenerated
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pressure_time_record.END_TIME
     *
     * @mbggenerated
     */
    private String endTime;
    /**
     * 租户id
     */
    @TableField(value = "customer_id",fill = FieldFill.INSERT)
    private long tenantId;
    /**
     * 用户id
     */
    private long userId;

    public long getTenantId() {
        return tenantId;
    }

    public void setTenantId(long tenantId) {
        this.tenantId = tenantId;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public String getEnvCode() {
        return envCode;
    }

    public void setEnvCode(String envCode) {
        this.envCode = envCode;
    }

    /**
     * 环境编码
     */
    @TableField(value = "env_code",fill = FieldFill.INSERT)
    private String envCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pressure_time_record
     *
     * @mbggenerated
     */
    public TPressureTimeRecord(String recordId, String startTime, String endTime) {
        this.recordId = recordId;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pressure_time_record
     *
     * @mbggenerated
     */
    public TPressureTimeRecord() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pressure_time_record.RECORD_ID
     *
     * @return the value of t_pressure_time_record.RECORD_ID
     * @mbggenerated
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pressure_time_record.RECORD_ID
     *
     * @param recordId the value for t_pressure_time_record.RECORD_ID
     * @mbggenerated
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pressure_time_record.START_TIME
     *
     * @return the value of t_pressure_time_record.START_TIME
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pressure_time_record.START_TIME
     *
     * @param startTime the value for t_pressure_time_record.START_TIME
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pressure_time_record.END_TIME
     *
     * @return the value of t_pressure_time_record.END_TIME
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pressure_time_record.END_TIME
     *
     * @param endTime the value for t_pressure_time_record.END_TIME
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }
}
