package com.pamirs.takin.entity.domain.entity;

public class TPressureTimeRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pressure_time_record.RECORD_ID
     *
     * @mbg generated
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pressure_time_record.START_TIME
     *
     * @mbg generated
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pressure_time_record.END_TIME
     *
     * @mbg generated
     */
    private String endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pressure_time_record
     *
     * @mbg generated
     */
    public TPressureTimeRecord(String recordId, String startTime, String endTime) {
        this.recordId = recordId;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pressure_time_record
     *
     * @mbg generated
     */
    public TPressureTimeRecord() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pressure_time_record.RECORD_ID
     *
     * @return the value of t_pressure_time_record.RECORD_ID
     * @mbg generated
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pressure_time_record.RECORD_ID
     *
     * @param recordId the value for t_pressure_time_record.RECORD_ID
     * @mbg generated
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pressure_time_record.START_TIME
     *
     * @return the value of t_pressure_time_record.START_TIME
     * @mbg generated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pressure_time_record.START_TIME
     *
     * @param startTime the value for t_pressure_time_record.START_TIME
     * @mbg generated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pressure_time_record.END_TIME
     *
     * @return the value of t_pressure_time_record.END_TIME
     * @mbg generated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pressure_time_record.END_TIME
     *
     * @param endTime the value for t_pressure_time_record.END_TIME
     * @mbg generated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }
}
