package com.pamirs.takin.entity.domain.entity;

import java.util.Date;

public class TShadowTableConfig extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shadow_table_config.ID
     *
     * @mbg generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shadow_table_config.SHADOW_TABLE_NAME
     *
     * @mbg generated
     */
    private String shadowTableName;

    /**
     * 数据源id
     */
    private Long shadowDatasourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shadow_table_config.ENABLE_STATUS
     *
     * @mbg generated
     */
    private Integer enableStatus;

    private Date createTime;

    private Date updateTime;

    public TShadowTableConfig(Long id, Long shadowDatasourceId, String shadowTableName, Integer enableStatus,
        Date createTime, Date updateTime) {
        this.id = id;
        this.shadowDatasourceId = shadowDatasourceId;
        this.shadowTableName = shadowTableName;
        this.enableStatus = enableStatus;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public TShadowTableConfig(Long id, Long shadowDatasourceId, String shadowTableName, Integer enableStatus) {
        this.id = id;
        this.shadowDatasourceId = shadowDatasourceId;
        this.shadowTableName = shadowTableName;
        this.enableStatus = enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shadow_table_config
     *
     * @mbg generated
     */
    public TShadowTableConfig() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shadow_table_config.ID
     *
     * @return the value of t_shadow_table_config.ID
     * @mbg generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shadow_table_config.ID
     *
     * @param id the value for t_shadow_table_config.ID
     * @mbg generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shadow_table_config.SHADOW_TABLE_NAME
     *
     * @return the value of t_shadow_table_config.SHADOW_TABLE_NAME
     * @mbg generated
     */
    public String getShadowTableName() {
        return shadowTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shadow_table_config.SHADOW_TABLE_NAME
     *
     * @param shadowTableName the value for t_shadow_table_config.SHADOW_TABLE_NAME
     * @mbg generated
     */
    public void setShadowTableName(String shadowTableName) {
        this.shadowTableName = shadowTableName == null ? null : shadowTableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shadow_table_config.ENABLE_STATUS
     *
     * @return the value of t_shadow_table_config.ENABLE_STATUS
     * @mbg generated
     */
    public Integer getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shadow_table_config.ENABLE_STATUS
     *
     * @param enableStatus the value for t_shadow_table_config.ENABLE_STATUS
     * @mbg generated
     */
    public void setEnableStatus(Integer enableStatus) {
        this.enableStatus = enableStatus;
    }

    @Override
    public Date getCreateTime() {
        return createTime;
    }

    @Override
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public Date getUpdateTime() {
        return updateTime;
    }

    @Override
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Long getShadowDatasourceId() {
        return shadowDatasourceId;
    }

    public void setShadowDatasourceId(Long shadowDatasourceId) {
        this.shadowDatasourceId = shadowDatasourceId;
    }

    @Override
    public String toString() {
        return "TShadowTableConfig{" +
            "id=" + id +
            ", shadowTableName='" + shadowTableName + '\'' +
            ", shadowDatasourceId=" + shadowDatasourceId +
            ", enableStatus=" + enableStatus +
            ", createTime=" + createTime +
            ", updateTime=" + updateTime +
            '}';
    }

}
