package com.pamirs.takin.entity.domain.entity;

import java.util.Date;

public class TShadowTableDataSource extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shadow_table_datasource.ID
     *
     * @mbg generated
     */
    private Long shadowDatasourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shadow_table_datasource.APPLICATION_ID
     *
     * @mbg generated
     */
    private Long applicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shadow_table_datasource.DATABASE_IPPORT
     *
     * @mbg generated
     */
    private String databaseIpport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shadow_table_datasource.DATABASE_NAME
     *
     * @mbg generated
     */
    private String databaseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shadow_table_datasource.USE_SHADOW_TABLE
     *
     * @mbg generated
     */
    private Integer useShadowTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shadow_table_datasource.CREATE_TIME
     *
     * @mbg generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shadow_table_datasource.UPDATE_TIME
     *
     * @mbg generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shadow_table_datasource
     *
     * @mbg generated
     */
    public TShadowTableDataSource(Long shadowDatasourceId, Long applicationId, String databaseIpport,
        String databaseName, Integer useShadowTable, Date createTime, Date updateTime) {
        this.shadowDatasourceId = shadowDatasourceId;
        this.applicationId = applicationId;
        this.databaseIpport = databaseIpport;
        this.databaseName = databaseName;
        this.useShadowTable = useShadowTable;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shadow_table_datasource
     *
     * @mbg generated
     */
    public TShadowTableDataSource() {
        super();
    }

    public Long getShadowDatasourceId() {
        return shadowDatasourceId;
    }

    public void setShadowDatasourceId(Long shadowDatasourceId) {
        this.shadowDatasourceId = shadowDatasourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shadow_table_datasource.APPLICATION_ID
     *
     * @return the value of t_shadow_table_datasource.APPLICATION_ID
     * @mbg generated
     */
    public Long getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shadow_table_datasource.APPLICATION_ID
     *
     * @param applicationId the value for t_shadow_table_datasource.APPLICATION_ID
     * @mbg generated
     */
    public void setApplicationId(Long applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shadow_table_datasource.DATABASE_IPPORT
     *
     * @return the value of t_shadow_table_datasource.DATABASE_IPPORT
     * @mbg generated
     */
    public String getDatabaseIpport() {
        return databaseIpport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shadow_table_datasource.DATABASE_IPPORT
     *
     * @param databaseIpport the value for t_shadow_table_datasource.DATABASE_IPPORT
     * @mbg generated
     */
    public void setDatabaseIpport(String databaseIpport) {
        this.databaseIpport = databaseIpport == null ? null : databaseIpport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shadow_table_datasource.DATABASE_NAME
     *
     * @return the value of t_shadow_table_datasource.DATABASE_NAME
     * @mbg generated
     */
    public String getDatabaseName() {
        return databaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shadow_table_datasource.DATABASE_NAME
     *
     * @param databaseName the value for t_shadow_table_datasource.DATABASE_NAME
     * @mbg generated
     */
    public void setDatabaseName(String databaseName) {
        this.databaseName = databaseName == null ? null : databaseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shadow_table_datasource.USE_SHADOW_TABLE
     *
     * @return the value of t_shadow_table_datasource.USE_SHADOW_TABLE
     * @mbg generated
     */
    public Integer getUseShadowTable() {
        return useShadowTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shadow_table_datasource.USE_SHADOW_TABLE
     *
     * @param useShadowTable the value for t_shadow_table_datasource.USE_SHADOW_TABLE
     * @mbg generated
     */
    public void setUseShadowTable(Integer useShadowTable) {
        this.useShadowTable = useShadowTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shadow_table_datasource.CREATE_TIME
     *
     * @return the value of t_shadow_table_datasource.CREATE_TIME
     * @mbg generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shadow_table_datasource.CREATE_TIME
     *
     * @param createTime the value for t_shadow_table_datasource.CREATE_TIME
     * @mbg generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shadow_table_datasource.UPDATE_TIME
     *
     * @return the value of t_shadow_table_datasource.UPDATE_TIME
     * @mbg generated
     */
    @Override
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shadow_table_datasource.UPDATE_TIME
     *
     * @param updateTime the value for t_shadow_table_datasource.UPDATE_TIME
     * @mbg generated
     */
    @Override
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
