package com.pamirs.takin.entity.dao.physicalisolation;

import java.util.List;

import com.pamirs.takin.entity.domain.entity.MqDeleteDTO;
import com.pamirs.takin.entity.domain.entity.MqIsolateConfig;
import org.apache.ibatis.annotations.Param;

public interface TMqIsolateConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbg generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbg generated
     */
    int insert(MqIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbg generated
     */
    int insertSelective(MqIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbg generated
     */
    MqIsolateConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbg generated
     */
    int updateByPrimaryKeySelective(MqIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbg generated
     */
    int updateByPrimaryKeyWithBLOBs(MqIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbg generated
     */
    int updateByPrimaryKey(MqIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbg generated
     */
    int queryConfigExsit(MqIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbg generated
     */
    List<MqIsolateConfig> queryMqIsolateConfigs(MqIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbg generated
     */
    List<MqIsolateConfig> queryMqIsolateConfig(@Param("ids") List<Long> ids);

    /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbg generated
     */
    List<MqIsolateConfig> queryAllActiveMqIsolateConfig();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mq_isolate_config
     *
     * @mbg generated
     */
    int deleteMqIsolateConfig(MqDeleteDTO dto);
}
