package com.pamirs.takin.entity.dao.physicalisolation;

import java.util.List;

import com.pamirs.takin.entity.domain.entity.NetworkIsolateConfig;
import org.apache.ibatis.annotations.Param;

public interface TNetworkIsolateConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_network_isolate_config
     *
     * @mbg generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_network_isolate_config
     *
     * @mbg generated
     */
    int insert(NetworkIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_network_isolate_config
     *
     * @mbg generated
     */
    int insertSelective(NetworkIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_network_isolate_config
     *
     * @mbg generated
     */
    NetworkIsolateConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_network_isolate_config
     *
     * @mbg generated
     */
    List<NetworkIsolateConfig> selectByAppName(String applicationName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_network_isolate_config
     *
     * @mbg generated
     */
    List<NetworkIsolateConfig> selectByAppNameList(@Param("names") List<String> names);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_network_isolate_config
     *
     * @mbg generated
     */
    List<NetworkIsolateConfig> selectIsoldateSuceessByAppNameList(@Param("names") List<String> names);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_network_isolate_config
     *
     * @mbg generated
     */
    int updateByPrimaryKeySelective(NetworkIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_network_isolate_config
     *
     * @mbg generated
     */
    int updateByPrimaryKeyWithBLOBs(NetworkIsolateConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_network_isolate_config
     *
     * @mbg generated
     */
    int updateByPrimaryKey(NetworkIsolateConfig record);

    int queryConfigExsit(NetworkIsolateConfig record);

    List<NetworkIsolateConfig> queryNetworkIsolateConfigs(NetworkIsolateConfig record);

    int deleteNetworkIsolateConfig(@Param("ids") List<Long> ids);

    List<NetworkIsolateConfig> queryNetworkIsolateConfig(@Param("ids") List<Long> ids);
}
