package com.pamirs.takin.entity.dao.confcenter;

import java.util.List;

import com.pamirs.takin.entity.domain.entity.TUploadInterfaceData;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TUploadInterfaceDataDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_interface_data
     *
     * @mbg generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_interface_data
     *
     * @mbg generated
     */
    int insert(TUploadInterfaceData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_interface_data
     *
     * @mbg generated
     */
    int insertSelective(TUploadInterfaceData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_interface_data
     *
     * @mbg generated
     */
    TUploadInterfaceData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_interface_data
     *
     * @mbg generated
     */
    int updateByPrimaryKeySelective(TUploadInterfaceData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upload_interface_data
     *
     * @mbg generated
     */
    int updateByPrimaryKey(TUploadInterfaceData record);

    /**
     * 批量插入
     *
     * @param recordList
     * @return
     */
    int insertList(@Param("list") List<TUploadInterfaceData> recordList);

    /**
     * 通过 appname 批量删除
     *
     * @param appName
     * @return
     */
    int deleteByAppName(@Param("appName") String appName);
}
