apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: shulie-takin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      hostAliases:
        - ip: "10.245.40.238"
          hostnames:
            - "skyeye.unicom.local"
        - ip: "10.245.29.215"
          hostnames:
            - "skyeye.unicom.local"
      containers:
      - name: web
        image: harbor.dcos.xixian.unicom.local/skyeye-platform-xx-pbc/stresstest/web:2.0.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "mkdir -p /data/nfs_dir && mount -o rw,intr,soft,timeo=30,retry=3,nolock -t nfs 10.238.52.214:/data/share /data/nfs_dir"
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
        resources:
          requests:
            memory: 4G
          limits:
            memory: 4G
        command: ["./start.sh" ]

