package com.pamirs.takin.entity.dao.transparentflow;

import com.pamirs.takin.entity.domain.entity.TPressureTimeRecord;
import org.apache.ibatis.annotations.Param;

public interface TPressureTimeRecordDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pressure_time_record
     *
     * @mbg generated
     */
    int insert(@Param("startTime") String startTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pressure_time_record
     *
     * @mbg generated
     */
    int updateByPrimaryKey(@Param("recordId") String recordId,
        @Param("endTime") String endTime);

    /**
     * 查询最大的开始压测时间
     *
     * @return
     */
    TPressureTimeRecord queryLatestPressureTime();

}
