CREATE TABLE aiops_shard_m.t_trace_expand (
        `appName` String,
        `entranceId` Nullable(String),
        `entranceNodeId` Nullable(String),
        `traceId` String,
        `level` Nullable(Int8),
        `parentIndex` Nullable(Int8),
        `index` Nullable(Int8),
        `rpcId` String,
        `rpcType` Int8,
        `startTime` Int64,
        `middlewareName` Nullable(String),
        `serviceName` Nullable(String),
        `methodName` Nullable(String),
        `requestSize` Nullable(String),
        `responseSize` Nullable(String),
        `request` Nullable(String),
        `response` Nullable(String),
        `clusterTest` Nullable(String),
        `callbackMsg` Nullable(String),
        `samplingInterval` Nullable(String),
        `localId` Nullable(String),
        `attributes` Nullable(String),
        `localAttributes` Nullable(String),
        `async` Nullable(String),
        `version` Nullable(String),
        `hostIp` Nullable(String),
        `agentId` Nullable(String),
        `startDate` DateTime,
        `createDate` DateTime DEFAULT toDateTime(now()),
        `timeMin` Nullable(Int64) DEFAULT 0,
        `entranceServiceType` Nullable(String),
        `parsedServiceName` String,
        `parsedMethod` String,
        `parsedAppName` Nullable(String),
        `parsedMiddlewareName` Nullable(String),
        `parsedExtend` Nullable(String),
        `dateToMin` Int64,
        `uploadTime` Nullable(Int64),
        `receiveHttpTime` Nullable(Int64),
        INDEX ix_traceid traceId TYPE minmax GRANULARITY 5,
        taskId Nullable(String),
        flag Nullable(String),
        flagMessage Nullable(String),
        receiveTime Nullable(Int64),
        processTime Nullable(Int64),
        saveCkTime DateTime DEFAULT now(),
        `userAppKey` String,
        `envCode` String,
        `userId` String,
        `logType` Int8
)
    ENGINE = ReplicatedMergeTree('/clickhouse/tables/cluster-aiops/t_trace_expand/{m_shard}', '{replica}')
PARTITION BY toYYYYMMDD(startDate)
ORDER BY (appName,startDate,parsedServiceName,parsedMethod,rpcType,rpcId)
TTL startDate + toIntervalDay(7)
SETTINGS index_granularity = 8192;

CREATE TABLE default.t_trace_expand_all as default.t_trace_expand ENGINE = Distributed('cluster-aiops', '', 't_trace_expand', sipHash64(traceId));
