UPDATE t_base_config SET CONFIG_VALUE = '[{
                "title": "系统概览",
                "path": "/dashboard",
                "type": "Item",
                "icon": "dashboard",
                "key": "dashboard",
                "children": null
        }, {
                "title": "仿真平台",
                "path": "/appPlatform",
                "type": "SubMenu",
                "icon": "shop",
                "key": "appManage",
                "children": [{
                        "title": "应用配置",
                        "path": "/appConfig",
                        "type": "SubMenu",
                        "icon": null,
                        "key": "appManage",
                        "children": [{
                                "title": "新应用接入",
                                "path": "/appAccess",
                                "type": "Item",
                                "icon": null,
                                "key": "appManage_appAccess",
                                "children": null
                        }, {
                                "title": "探针列表",
                                "path": "/pro/nodeManage",
                                "type": "Item",
                                "icon": null,
                                "key": "appManage_agentManage",
                                "children": null
                        }, {
                                "title": "应用管理",
                                "path": "/appManage",
                                "type": "Item",
                                "icon": null,
                                "key": "appManage",
                                "children": [{
                                        "title": "应用详情",
                                        "path": "/appManages/details",
                                        "type": "NoMenu",
                                        "icon": null,
                                        "key": "appManage",
                                        "children": null
                                }]
                        }]
                }, {
                        "title": "链路管理",
                        "path": "/linkManage",
                        "type": "SubMenu",
                        "icon": null,
                        "key": "linkTease",
                        "children": [{
                                "title": "入口规则",
                                "path": "/configCenter/entryRule",
                                "type": "Item",
                                "icon": null,
                                "key": "configCenter_entryRule",
                                "children": null
                        }, {
                                "title": "业务活动",
                                "path": "/businessActivity",
                                "type": "Item",
                                "icon": null,
                                "key": "businessActivity",
                                "children": [{
                                        "title": "新增业务活动",
                                        "path": "/businessActivity/addEdit",
                                        "type": "NoMenu",
                                        "icon": null,
                                        "key": "businessActivity",
                                        "children": null
                                }]
                        }, {
                                "title": "业务流程",
                                "path": "/businessFlow",
                                "type": "Item",
                                "icon": null,
                                "key": "businessFlow",
                                "children": [{
                                        "title": "新增业务流程",
                                        "path": "/businessFlow/addBusinessFlow",
                                        "type": "NoMenu",
                                        "icon": null,
                                        "key": "businessFlow",
                                        "children": null
                                }]
                        }, {
                                "title": "回放流量数据配置",
                                "path": "/flowback",
                                "type": "Item",
                                "icon": null,
                                "key": "flowback"
                        }]
                }, {
                        "title": "脚本管理",
                        "path": "/scriptManages",
                        "type": "SubMenu",
                        "icon": null,
                        "key": "scriptManages",
                        "children": [{
                                "title": "测试脚本",
                                "path": "/scriptManage",
                                "type": "Item",
                                "icon": null,
                                "key": "scriptManage",
                                "children": [{
                                        "title": "脚本配置",
                                        "path": "/scriptManage/scriptConfig",
                                        "type": "NoMenu",
                                        "icon": null,
                                        "key": "scriptManage",
                                        "children": null
                                }, {
                                        "title": "脚本调试详情",
                                        "path": "/scriptManage/scriptDebugDetail",
                                        "type": "NoMenu",
                                        "icon": null,
                                        "key": "scriptManage",
                                        "children": null
                                }]
                        }]
                }, {
                        "title": "调试工具",
                        "path": "/debugTool",
                        "type": "SubMenu",
                        "icon": null,
                        "key": "debugTool",
                        "children": [{
                                "title": "链路调试",
                                "path": "/pro/debugTool/linkDebug",
                                "type": "Item",
                                "icon": null,
                                "key": "debugTool_linkDebug",
                                "children": [{
                                        "title": "链路调试详情",
                                        "path": "/pro/debugTool/linkDebug/detail",
                                        "type": "NoMenu",
                                        "icon": null,
                                        "key": "debugTool_linkDebug",
                                        "children": null
                                }]
                        }]
                }, {
                        "title": "数据源管理",
                        "path": "/dataSourceManage",
                        "type": "SubMenu",
                        "icon": null,
                        "key": null,
                        "children": [{
                                "title": "数据源配置",
                                "path": "/configCenter/dataSourceConfig",
                                "type": "Item",
                                "icon": null,
                                "key": "configCenter_dataSourceConfig",
                                "children": null
                        }]
                }]
        }, {
                "title": "压测平台",
                "path": "/hourglass",
                "type": "SubMenu",
                "icon": "hourglass",
                "key": null,
                "children": [{
                        "title": "压测管理",
                        "path": "/pressureTestManage",
                        "type": "SubMenu",
                        "icon": null,
                        "key": null,
                        "children": [{
                                        "title": "压测场景",
                                        "path": "/pressureTestManage/pressureTestScene",
                                        "type": "Item",
                                        "icon": null,
                                        "key": "pressureTestManage_pressureTestScene",
                                        "children": [{
                                                "title": "压测场景配置",
                                                "path": "/pressureTestManage/pressureTestScene/pressureTestSceneConfig",
                                                "type": "NoMenu",
                                                "icon": null,
                                                "key": "pressureTestManage_pressureTestScene",
                                                "children": null
                                        }],
                                }, {
                                        "title": "Takin压测",
                                        "path": "/pressureTestManage/testByInterface",
                                        "type": "Item",
                                        "icon": null,
                                        "key": "pressureTestManage_testByInterface"
                                },
                                {
                                        "title": "压测报告",
                                        "path": "/pressureTestManage/pressureTestReport",
                                        "type": "Item",
                                        "icon": null,
                                        "key": "pressureTestManage_pressureTestReport",
                                        "children": [{
                                                "title": "压测实况",
                                                "path": "/pressureTestManage/pressureTestReport/pressureTestLive",
                                                "type": "NoMenu",
                                                "icon": null,
                                                "key": "pressureTestManage_pressureTestReport",
                                                "children": null
                                        }, {
                                                "title": "压测报告详请",
                                                "path": "/pressureTestManage/pressureTestReport/details",
                                                "type": "NoMenu",
                                                "icon": null,
                                                "key": "pressureTestManage_pressureTestReport",
                                                "children": null
                                        }]
                                },
                                {
                                        "title": "回收站",
                                        "type": "Item",
                                        "key": "pressureTestManage_recycle",
                                        "path": "/pressureTestManage/pressureTestScene/recycle"
                                }
                        ]
                }]
        },
        {
                "title": "巡检平台",
                "path": "/accountBook",
                "type": "SubMenu",
                "icon": "account-book",
                "key": "patrolScreen",
                "children": [{
                        "title": "巡检大盘",
                        "path": "/pro/e2eBigScreen",
                        "type": "Item",
                        "icon": "account-book",
                        "key": "patrolScreen",
                        "children": null
                }, {
                        "title": "巡检管理",
                        "path": "/pro/missionManage",
                        "type": "Item",
                        "icon": "account-book",
                        "key": "patrolBoard",
                        "children": [{
                                "title": "巡检场景详情",
                                "path": "/pro/missionManage/sceneDetails",
                                "type": "NoMenu",
                                "icon": null,
                                "key": "patrolManage",
                                "children": null
                        }]
                }, {
                        "title": "瓶颈列表",
                        "path": "/pro/bottleneckTable",
                        "type": "Item",
                        "icon": "unordered-list",
                        "key": "bottleneckTable",
                        "children": [{
                                "title": "瓶颈详情",
                                "path": "/pro/bottleneckTable/bottleneckDetails",
                                "type": "NoMenu",
                                "icon": null,
                                "key": "bottleneckTable",
                                "children": null
                        }]
                }, {
                        "title": "瓶颈通知",
                        "path": "/pro/faultNotification",
                        "type": "Item",
                        "icon": "menu-unfold",
                        "key": "exceptionNoticeManage",
                        "children": null
                }, {
                        "title": "配置中心",
                        "path": "/pro/setFocus",
                        "type": "Item",
                        "icon": "setting",
                        "key": "bottleneckConfig",
                        "children": null
                }]
        },
        {
                "title": "性能监控",
                "path": "/tracks",
                "type": "SubMenu",
                "icon": "form",
                "key": "tracks",
                "children": [{
                        "title": "链路查询",
                        "path": "/pro/track",
                        "type": "Item",
                        "icon": null,
                        "key": "traceQuery",
                        "children": null
                }]
        },
        {
                "title": "设置中心",
                "path": "/setting",
                "type": "SubMenu",
                "icon": "setting",
                "key": "configCenter",
                "children": [{
                        "title": "系统管理",
                        "path": "/configCenter",
                        "type": "SubMenu",
                        "icon": null,
                        "key": "configCenter",
                        "children": [{
                                "title": "系统信息",
                                "path": "/configCenter/systemInfo",
                                "type": "Item",
                                "icon": null,
                                "key": "system_info",
                                "children": null
                        }, {
                                "title": "全局配置",
                                "path": "/configCenter/globalConfig",
                                "type": "Item",
                                "icon": null,
                                "key": "center_config",
                                "children": [{
                                        "title": "压测开关",
                                        "path": "",
                                        "type": "NoMenu",
                                        "icon": null,
                                        "key": "configCenter_pressureMeasureSwitch",
                                        "children": null
                                }, {
                                        "title": "白名单开关",
                                        "path": "",
                                        "type": "NoMenu",
                                        "icon": null,
                                        "key": "configCenter_whitelistSwitch",
                                        "children": null
                                }]
                        }, {
                                "title": "中间件库管理",
                                "path": "/configCenter/middlewareManage",
                                "type": "Item",
                                "icon": null,
                                "key": "configCenter_middlewareManage",
                                "children": null
                        }, {
                                "title": "开关配置",
                                "path": "/configCenter/bigDataConfig",
                                "type": "Item",
                                "icon": null,
                                "key": "configCenter_bigDataConfig",
                                "children": null
                        }, {
                                "title": "探针版本管理",
                                "path": "/pro/admin",
                                "type": "Item",
                                "icon": null,
                                "key": "admins_admin",
                                "children": null
                        }, {
                                "title": "仿真系统配置",
                                "path": "/simulationConfig",
                                "type": "Item",
                                "icon": null,
                                "key": "admins_simulationConfig",
                                "children": null
                        }, {
                                "title": "流量账户",
                                "path": "/pro/flowAccount",
                                "type": "Item",
                                "icon": null,
                                "key": "flowAccount",
                                "children": null
                        }]
                }, {
                        "title": "权限管理",
                        "path": "/authorityManage",
                        "type": "SubMenu",
                        "icon": null,
                        "key": "configCenter_authorityConfig",
                        "children": [{
                                "title": "权限配置中心",
                                "path": "/pro/configCenter/authorityConfig",
                                "type": "Item",
                                "icon": null,
                                "key": "configCenter_authorityConfig",
                                "children": null
                        }, {
                                "title": "操作日志",
                                "path": "/pro/configCenter/operationLog",
                                "type": "Item",
                                "icon": null,
                                "key": "configCenter_operationLog",
                                "children": null
                        }]
                }, {
                        "title": "安全中心",
                        "path": "/securityCenter",
                        "type": "SubMenu",
                        "icon": null,
                        "key": "securityCenter",
                        "children": [{
                                "title": "脱敏策略",
                                "path": "/pro/securityCenter/desensitizePolicysManage",
                                "type": "Item",
                                "icon": null,
                                "key": "securityCenter_desensitizePolicysManage",
                                "children": null
                        }, {
                                "title": "限流配置",
                                "path": "/pro/securityCenter/trafficConfig",
                                "type": "Item",
                                "icon": null,
                                "key": "securityCenter_trafficConfig",
                                "children": null
                        }, {
                                "title": "秘钥对配置",
                                "path": "/pro/securityCenter/keysConfig",
                                "type": "Item",
                                "icon": null,
                                "key": "securityCenter_keysConfig",
                                "children": null
                        }]
                }]
        }
]' WHERE CONFIG_CODE = 'ALL_MENU';